// Code generated by re2go 4.1 on Wed Jun 25 12:35:44 2025, DO NOT EDIT.
//
//line "_lexer.go":1
//go:generate re2go -o lexer.go _lexer.go
package clustering

//line "_lexer.go":12

func Lex(input string, tokens []Token) []Token {
	cursor := 0
	marker := 0
	limit := len(input)

	// Convert string to byte slice for re2c compatibility
	inputBytes := []byte(input)

	for cursor < limit {
		tokenStart := cursor

//line "lexer.go":22
		{
			var yych byte
			yyaccept := 0
			yych = peek(inputBytes, cursor)
			switch yych {
			case 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08:
				fallthrough
			case '\v', '\f':
				fallthrough
			case 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F:
				fallthrough
			case '#', '$', '%', '&':
				fallthrough
			case '*', '+':
				fallthrough
			case '-':
				fallthrough
			case '=', '>':
				fallthrough
			case '@':
				fallthrough
			case '\\':
				fallthrough
			case '^', '_', '`':
				fallthrough
			case '|':
				fallthrough
			case '~', 0x7F:
				goto yy2
			case '\t', '\n':
				fallthrough
			case '\r':
				fallthrough
			case ' ':
				goto yy4
			case '!', '"':
				fallthrough
			case '\'', '(', ')':
				fallthrough
			case ',':
				fallthrough
			case '.':
				fallthrough
			case ':', ';':
				fallthrough
			case '?':
				fallthrough
			case ']':
				fallthrough
			case '{':
				fallthrough
			case '}':
				goto yy6
			case '/':
				goto yy8
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy9
			case '<':
				goto yy11
			case 'A':
				goto yy12
			case 'B':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy14
			case 'C':
				goto yy15
			case 'D':
				goto yy16
			case 'E':
				goto yy17
			case 'F':
				goto yy18
			case 'G':
				goto yy19
			case 'H':
				goto yy20
			case 'I':
				goto yy21
			case 'J', 'K', 'L', 'M':
				fallthrough
			case 'Q', 'R', 'S':
				fallthrough
			case 'U', 'V':
				fallthrough
			case 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy22
			case 'N':
				goto yy23
			case 'O':
				goto yy24
			case 'P':
				goto yy25
			case 'T':
				goto yy26
			case 'W':
				goto yy27
			case '[':
				goto yy28
			case 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF:
				goto yy29
			case 0xE0:
				goto yy30
			case 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF:
				goto yy31
			case 0xF0:
				goto yy32
			case 0xF1, 0xF2, 0xF3:
				goto yy33
			case 0xF4:
				goto yy34
			default:
				goto yy1
			}
		yy1:
			cursor = marker
			switch yyaccept {
			case 0:
				goto yy10
			case 1:
				goto yy3
			case 2:
				goto yy13
			case 3:
				goto yy7
			case 4:
				goto yy82
			case 5:
				goto yy112
			case 6:
				goto yy114
			case 7:
				goto yy221
			default:
				goto yy274
			}
		yy2:
			cursor += 1
		yy3:
//line "_lexer.go":155
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: string(inputBytes[cursor-1]), Type: Special})
				}
				continue
			}
//line "lexer.go":171
		yy4:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\r':
				fallthrough
			case ' ':
				goto yy4
			default:
				goto yy5
			}
		yy5:
//line "_lexer.go":27
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: Special})
				}
				continue
			}
//line "lexer.go":193
		yy6:
			cursor += 1
		yy7:
//line "_lexer.go":148
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: Special})
				}
				continue
			}
//line "lexer.go":204
		yy8:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy35
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy37
			default:
				goto yy3
			}
		yy9:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '.':
				goto yy38
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy39
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy40
			default:
				goto yy10
			}
		yy10:
//line "_lexer.go":132
			{
				if cursor <= limit {
					tp := Number
					if isHTTPCode(input[tokenStart:cursor]) {
						tp = HTTPCode
					}
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: tp})
				}
				continue
			}
//line "lexer.go":251
		yy11:
			yyaccept = 1
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy41
			default:
				goto yy3
			}
		yy12:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '_':
				goto yy42
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy44
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy45
			case 'G', 'H', 'I', 'J', 'K':
				fallthrough
			case 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'L':
				goto yy47
			default:
				goto yy13
			}
		yy13:
//line "_lexer.go":141
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: Word})
				}
				continue
			}
//line "lexer.go":298
		yy14:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '_':
				goto yy42
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy44
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy45
			case 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			default:
				goto yy13
			}
		yy15:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '_':
				goto yy42
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy44
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy45
			case 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N':
				fallthrough
			case 'P', 'Q':
				fallthrough
			case 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'O':
				goto yy48
			case 'R':
				goto yy49
			default:
				goto yy13
			}
		yy16:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '_':
				goto yy42
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy44
			case 'A', 'B', 'C', 'D':
				fallthrough
			case 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy45
			case 'E':
				goto yy50
			case 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			default:
				goto yy13
			}
		yy17:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '_':
				goto yy42
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy44
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy45
			case 'G', 'H', 'I', 'J', 'K', 'L':
				fallthrough
			case 'N', 'O', 'P', 'Q':
				fallthrough
			case 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'M':
				goto yy51
			case 'R':
				goto yy52
			default:
				goto yy13
			}
		yy18:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '_':
				goto yy42
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy44
			case 'A':
				goto yy53
			case 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy45
			case 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			default:
				goto yy13
			}
		yy19:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D':
				fallthrough
			case 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'E':
				goto yy54
			default:
				goto yy13
			}
		yy20:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D':
				fallthrough
			case 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S':
				fallthrough
			case 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'E':
				goto yy55
			case 'T':
				goto yy56
			default:
				goto yy13
			}
		yy21:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M':
				fallthrough
			case 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'N':
				goto yy57
			default:
				goto yy13
			}
		yy22:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			default:
				goto yy13
			}
		yy23:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N':
				fallthrough
			case 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'O':
				goto yy58
			default:
				goto yy13
			}
		yy24:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O':
				fallthrough
			case 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'P':
				goto yy59
			default:
				goto yy13
			}
		yy25:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A':
				goto yy60
			case 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N':
				fallthrough
			case 'P', 'Q', 'R', 'S', 'T':
				fallthrough
			case 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'O':
				goto yy61
			case 'U':
				goto yy54
			default:
				goto yy13
			}
		yy26:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q':
				fallthrough
			case 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case 'R':
				goto yy62
			default:
				goto yy13
			}
		yy27:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A':
				goto yy63
			case 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			default:
				goto yy13
			}
		yy28:
			yyaccept = 3
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy64
			default:
				goto yy7
			}
		yy29:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy2
			default:
				goto yy1
			}
		yy30:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy29
			default:
				goto yy1
			}
		yy31:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy29
			default:
				goto yy1
			}
		yy32:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy31
			default:
				goto yy1
			}
		yy33:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy31
			default:
				goto yy1
			}
		yy34:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F:
				goto yy31
			default:
				goto yy1
			}
		yy35:
			cursor += 1
		yy36:
//line "_lexer.go":101
			{
				if input[cursor-1] == ' ' {
					cursor--
				}
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: HTTPPathPart})
				}
				continue
			}
//line "lexer.go":725
		yy37:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy37
			default:
				goto yy36
			}
		yy38:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy65
			default:
				goto yy1
			}
		yy39:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '.':
				goto yy38
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy66
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy67
			default:
				goto yy10
			}
		yy40:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy67
			default:
				goto yy1
			}
		yy41:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy41
			case '>':
				goto yy68
			default:
				goto yy1
			}
		yy42:
			cursor += 1
			yych = peek(inputBytes, cursor)
		yy43:
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy42
			case '[':
				goto yy69
			default:
				goto yy1
			}
		yy44:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy70
			default:
				goto yy43
			}
		yy45:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '_':
				goto yy42
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy70
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy71
			case 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy46:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy47:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D':
				fallthrough
			case 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'E':
				goto yy73
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy48:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M':
				fallthrough
			case 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'N':
				goto yy74
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy49:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H':
				fallthrough
			case 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'I':
				goto yy75
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy50:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '_':
				goto yy42
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy70
			case 'A':
				fallthrough
			case 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy71
			case 'B':
				goto yy76
			case 'G', 'H', 'I', 'J', 'K':
				fallthrough
			case 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'L':
				goto yy77
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy51:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D':
				fallthrough
			case 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'E':
				goto yy78
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy52:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q':
				fallthrough
			case 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'R':
				goto yy79
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy53:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '_':
				goto yy42
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy70
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy71
			case 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S':
				fallthrough
			case 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'T':
				goto yy80
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy54:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S':
				fallthrough
			case 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'T':
				goto yy81
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy55:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A':
				goto yy83
			case 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy56:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S':
				fallthrough
			case 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'T':
				goto yy84
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy57:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E':
				fallthrough
			case 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'F':
				goto yy85
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy58:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S':
				fallthrough
			case 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'T':
				goto yy86
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy59:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S':
				fallthrough
			case 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'T':
				goto yy87
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy60:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S':
				fallthrough
			case 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'T':
				goto yy88
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy61:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R':
				fallthrough
			case 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'S':
				goto yy89
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy62:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A':
				goto yy90
			case 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy63:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q':
				fallthrough
			case 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case 'R':
				goto yy91
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy64:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy92
			default:
				goto yy1
			}
		yy65:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '.':
				goto yy93
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy65
			default:
				goto yy10
			}
		yy66:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '.':
				goto yy38
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy94
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy95
			default:
				goto yy10
			}
		yy67:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy95
			default:
				goto yy1
			}
		yy68:
			cursor += 1
//line "_lexer.go":41
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: Priority})
				}
				continue
			}
//line "lexer.go":1366
		yy69:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy96
			default:
				goto yy1
			}
		yy70:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy97
			default:
				goto yy43
			}
		yy71:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy97
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy99
			default:
				goto yy101
			}
		yy72:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			default:
				goto yy101
			}
		yy73:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'R':
				goto yy102
			default:
				goto yy101
			}
		yy74:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'N':
				goto yy103
			default:
				goto yy101
			}
		yy75:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'T':
				goto yy104
			default:
				goto yy101
			}
		yy76:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy97
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy99
			case 'U':
				goto yy105
			default:
				goto yy101
			}
		yy77:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'E':
				goto yy106
			default:
				goto yy101
			}
		yy78:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'R':
				goto yy107
			default:
				goto yy101
			}
		yy79:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'O':
				goto yy108
			default:
				goto yy101
			}
		yy80:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'A':
				goto yy109
			default:
				goto yy101
			}
		yy81:
			yyaccept = 4
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy101
			default:
				goto yy82
			}
		yy82:
//line "_lexer.go":125
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: HTTPMethod})
				}
				continue
			}
//line "lexer.go":1556
		yy83:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'D':
				goto yy110
			default:
				goto yy101
			}
		yy84:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'P':
				goto yy111
			default:
				goto yy101
			}
		yy85:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'O':
				goto yy113
			default:
				goto yy101
			}
		yy86:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'I':
				goto yy115
			default:
				goto yy101
			}
		yy87:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'I':
				goto yy116
			default:
				goto yy101
			}
		yy88:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'C':
				goto yy117
			default:
				goto yy101
			}
		yy89:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'T':
				goto yy110
			default:
				goto yy101
			}
		yy90:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'C':
				goto yy118
			default:
				goto yy101
			}
		yy91:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy98
			case 'N':
				goto yy119
			default:
				goto yy101
			}
		yy92:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '/':
				goto yy120
			default:
				goto yy1
			}
		yy93:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy121
			default:
				goto yy1
			}
		yy94:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy122
			case '.':
				goto yy38
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy123
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy124
			default:
				goto yy10
			}
		yy95:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy124
			default:
				goto yy1
			}
		yy96:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy96
			case ']':
				goto yy125
			default:
				goto yy1
			}
		yy97:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy126
			default:
				goto yy43
			}
		yy98:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy127
			default:
				goto yy1
			}
		yy99:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy126
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy128
			default:
				goto yy101
			}
		yy100:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
		yy101:
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '_':
				goto yy42
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy100
			case '[':
				goto yy69
			default:
				goto yy13
			}
		yy102:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'T':
				goto yy113
			default:
				goto yy101
			}
		yy103:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'E':
				goto yy129
			default:
				goto yy101
			}
		yy104:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'I':
				goto yy130
			default:
				goto yy101
			}
		yy105:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'G':
				goto yy113
			default:
				goto yy101
			}
		yy106:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'T':
				goto yy118
			default:
				goto yy101
			}
		yy107:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'G':
				goto yy131
			default:
				goto yy101
			}
		yy108:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'R':
				goto yy113
			default:
				goto yy101
			}
		yy109:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'L':
				goto yy113
			default:
				goto yy101
			}
		yy110:
			yyaccept = 4
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy101
			default:
				goto yy82
			}
		yy111:
			yyaccept = 5
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy101
			case '/':
				goto yy132
			default:
				goto yy112
			}
		yy112:
//line "_lexer.go":111
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: HTTPVersion})
				}
				continue
			}
//line "lexer.go":1930
		yy113:
			yyaccept = 6
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy101
			default:
				goto yy114
			}
		yy114:
//line "_lexer.go":70
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: LogLevel})
				}
				continue
			}
//line "lexer.go":1958
		yy115:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'C':
				goto yy133
			default:
				goto yy101
			}
		yy116:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'O':
				goto yy134
			default:
				goto yy101
			}
		yy117:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'H':
				goto yy110
			default:
				goto yy101
			}
		yy118:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'E':
				goto yy110
			default:
				goto yy101
			}
		yy119:
			yyaccept = 6
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H':
				fallthrough
			case 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy101
			case 'I':
				goto yy135
			default:
				goto yy114
			}
		yy120:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy136
			default:
				goto yy1
			}
		yy121:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '.':
				goto yy137
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy121
			default:
				goto yy1
			}
		yy122:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy138
			default:
				goto yy1
			}
		yy123:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '.':
				goto yy38
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy139
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy140
			default:
				goto yy10
			}
		yy124:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy140
			default:
				goto yy1
			}
		yy125:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ':':
				goto yy141
			default:
				goto yy1
			}
		yy126:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy142
			default:
				goto yy43
			}
		yy127:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy143
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy144
			default:
				goto yy1
			}
		yy128:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy142
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy145
			default:
				goto yy101
			}
		yy129:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'C':
				goto yy146
			default:
				goto yy101
			}
		yy130:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'C':
				goto yy147
			default:
				goto yy101
			}
		yy131:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'E':
				goto yy148
			default:
				goto yy101
			}
		yy132:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '1', '2':
				goto yy149
			default:
				goto yy1
			}
		yy133:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'E':
				goto yy113
			default:
				goto yy101
			}
		yy134:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'N':
				goto yy150
			default:
				goto yy101
			}
		yy135:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'N':
				goto yy105
			default:
				goto yy101
			}
		yy136:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy151
			default:
				goto yy1
			}
		yy137:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy152
			default:
				goto yy1
			}
		yy138:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy154
			default:
				goto yy1
			}
		yy139:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '.':
				goto yy38
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy155
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy156
			default:
				goto yy10
			}
		yy140:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy156
			default:
				goto yy1
			}
		yy141:
			cursor += 1
//line "_lexer.go":77
			{
				if cursor <= limit {
					// Extract program name and PID separately
					pidStart := -1
					pidEnd := -1
					for i := tokenStart; i < cursor; i++ {
						if inputBytes[i] == '[' {
							pidStart = i + 1
						} else if inputBytes[i] == ']' {
							pidEnd = i
							break
						}
					}
					if pidStart > -1 && pidEnd > -1 {
						tokens = append(tokens, Token{Value: input[tokenStart : pidStart-1], Type: ProgramName})
						tokens = append(tokens, Token{Value: input[pidStart:pidEnd], Type: PID})
						tokens = append(tokens, Token{Value: input[pidEnd:cursor], Type: Special})
					} else {
						tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: ProgramName})
					}
				}
				continue
			}
//line "lexer.go":2295
		yy142:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy157
			default:
				goto yy43
			}
		yy143:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy158
			default:
				goto yy1
			}
		yy144:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				goto yy143
			default:
				goto yy1
			}
		yy145:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy157
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy159
			default:
				goto yy101
			}
		yy146:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'T':
				goto yy110
			default:
				goto yy101
			}
		yy147:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'A':
				goto yy109
			default:
				goto yy101
			}
		yy148:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'N':
				goto yy160
			default:
				goto yy101
			}
		yy149:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '.':
				goto yy161
			default:
				goto yy1
			}
		yy150:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'S':
				goto yy110
			default:
				goto yy101
			}
		yy151:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy162
			default:
				goto yy1
			}
		yy152:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy152
			default:
				goto yy153
			}
		yy153:
//line "_lexer.go":118
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: IPAddress})
				}
				continue
			}
//line "lexer.go":2423
		yy154:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy163
			default:
				goto yy1
			}
		yy155:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '.':
				goto yy38
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy164
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy165
			default:
				goto yy10
			}
		yy156:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy165
			default:
				goto yy1
			}
		yy157:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy166
			default:
				goto yy43
			}
		yy158:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy167
			default:
				goto yy1
			}
		yy159:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy166
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy168
			default:
				goto yy101
			}
		yy160:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'C':
				goto yy169
			default:
				goto yy101
			}
		yy161:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1':
				goto yy170
			default:
				goto yy1
			}
		yy162:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '/':
				goto yy171
			default:
				goto yy1
			}
		yy163:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy172
			default:
				goto yy1
			}
		yy164:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy173
			default:
				goto yy175
			}
		yy165:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy173
			default:
				goto yy1
			}
		yy166:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy176
			default:
				goto yy43
			}
		yy167:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ':':
				goto yy177
			default:
				goto yy1
			}
		yy168:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy176
			default:
				goto yy101
			}
		yy169:
			yyaccept = 2
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'Y':
				goto yy113
			default:
				goto yy101
			}
		yy170:
			cursor += 1
			goto yy112
		yy171:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy178
			default:
				goto yy1
			}
		yy172:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy179
			default:
				goto yy1
			}
		yy173:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy180
			default:
				goto yy1
			}
		yy174:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
		yy175:
			switch yych {
			case '.':
				goto yy38
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy174
			default:
				goto yy10
			}
		yy176:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy181
			default:
				goto yy43
			}
		yy177:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy182
			default:
				goto yy1
			}
		yy178:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy183
			default:
				goto yy1
			}
		yy179:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case 'T':
				goto yy184
			default:
				goto yy1
			}
		yy180:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy185
			default:
				goto yy1
			}
		yy181:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy186
			default:
				goto yy43
			}
		yy182:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy187
			default:
				goto yy1
			}
		yy183:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy188
			default:
				goto yy1
			}
		yy184:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy189
			default:
				goto yy1
			}
		yy185:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy190
			default:
				goto yy1
			}
		yy186:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy191
			default:
				goto yy43
			}
		yy187:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ':':
				goto yy192
			default:
				goto yy1
			}
		yy188:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy193
			default:
				goto yy1
			}
		yy189:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy194
			default:
				goto yy1
			}
		yy190:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy195
			default:
				goto yy1
			}
		yy191:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy196
			default:
				goto yy43
			}
		yy192:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy197
			default:
				goto yy1
			}
		yy193:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ':':
				goto yy198
			default:
				goto yy1
			}
		yy194:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ':':
				goto yy199
			default:
				goto yy1
			}
		yy195:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy200
			default:
				goto yy1
			}
		yy196:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy201
			default:
				goto yy43
			}
		yy197:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy202
			default:
				goto yy1
			}
		yy198:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy203
			default:
				goto yy1
			}
		yy199:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy204
			default:
				goto yy1
			}
		yy200:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy205
			default:
				goto yy1
			}
		yy201:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy206
			default:
				goto yy43
			}
		yy202:
			cursor += 1
//line "_lexer.go":63
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: Timestamp})
				}
				continue
			}
//line "lexer.go":2925
		yy203:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy207
			default:
				goto yy1
			}
		yy204:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy208
			default:
				goto yy1
			}
		yy205:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy209
			default:
				goto yy1
			}
		yy206:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy210
			default:
				goto yy43
			}
		yy207:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ':':
				goto yy211
			default:
				goto yy1
			}
		yy208:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ':':
				goto yy212
			default:
				goto yy1
			}
		yy209:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy213
			default:
				goto yy1
			}
		yy210:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy214
			default:
				goto yy43
			}
		yy211:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy215
			default:
				goto yy1
			}
		yy212:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy216
			default:
				goto yy1
			}
		yy213:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy217
			default:
				goto yy1
			}
		yy214:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy218
			default:
				goto yy43
			}
		yy215:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy219
			default:
				goto yy1
			}
		yy216:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy220
			default:
				goto yy1
			}
		yy217:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy222
			default:
				goto yy1
			}
		yy218:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy223
			default:
				goto yy43
			}
		yy219:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ':':
				goto yy224
			default:
				goto yy1
			}
		yy220:
			yyaccept = 7
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '+':
				fallthrough
			case '-':
				goto yy225
			case '.':
				goto yy226
			case 'Z':
				goto yy227
			default:
				goto yy221
			}
		yy221:
//line "_lexer.go":49
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: Timestamp})
				}
				continue
			}
//line "lexer.go":3128
		yy222:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy228
			default:
				goto yy1
			}
		yy223:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy229
			default:
				goto yy43
			}
		yy224:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy230
			default:
				goto yy1
			}
		yy225:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy231
			default:
				goto yy1
			}
		yy226:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy232
			default:
				goto yy1
			}
		yy227:
			cursor += 1
			goto yy221
		yy228:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy233
			default:
				goto yy1
			}
		yy229:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy234
			default:
				goto yy43
			}
		yy230:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy235
			default:
				goto yy1
			}
		yy231:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy236
			default:
				goto yy1
			}
		yy232:
			yyaccept = 7
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '+':
				fallthrough
			case '-':
				goto yy225
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy232
			case 'Z':
				goto yy227
			default:
				goto yy221
			}
		yy233:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy237
			default:
				goto yy1
			}
		yy234:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy238
			default:
				goto yy43
			}
		yy235:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ' ':
				fallthrough
			case '+':
				fallthrough
			case '-':
				goto yy239
			default:
				goto yy1
			}
		yy236:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ':':
				goto yy240
			default:
				goto yy1
			}
		yy237:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy241
			default:
				goto yy1
			}
		yy238:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy242
			default:
				goto yy43
			}
		yy239:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy243
			default:
				goto yy1
			}
		yy240:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy244
			default:
				goto yy1
			}
		yy241:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy245
			default:
				goto yy1
			}
		yy242:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				goto yy246
			default:
				goto yy43
			}
		yy243:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy247
			default:
				goto yy1
			}
		yy244:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy227
			default:
				goto yy1
			}
		yy245:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy248
			default:
				goto yy1
			}
		yy246:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy249
			default:
				goto yy43
			}
		yy247:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy250
			default:
				goto yy1
			}
		yy248:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy251
			default:
				goto yy1
			}
		yy249:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy252
			default:
				goto yy43
			}
		yy250:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy253
			default:
				goto yy1
			}
		yy251:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy254
			default:
				goto yy1
			}
		yy252:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy255
			default:
				goto yy43
			}
		yy253:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case ']':
				goto yy256
			default:
				goto yy1
			}
		yy254:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy257
			default:
				goto yy1
			}
		yy255:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy258
			default:
				goto yy43
			}
		yy256:
			cursor += 1
//line "_lexer.go":56
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: Timestamp})
				}
				continue
			}
//line "lexer.go":3514
		yy257:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy259
			default:
				goto yy1
			}
		yy258:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy260
			default:
				goto yy43
			}
		yy259:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy261
			default:
				goto yy1
			}
		yy260:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy262
			default:
				goto yy43
			}
		yy261:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy263
			default:
				goto yy1
			}
		yy262:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy264
			default:
				goto yy43
			}
		yy263:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy265
			default:
				goto yy1
			}
		yy264:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy266
			default:
				goto yy43
			}
		yy265:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy267
			default:
				goto yy1
			}
		yy266:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy268
			default:
				goto yy43
			}
		yy267:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy269
			default:
				goto yy1
			}
		yy268:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy270
			default:
				goto yy43
			}
		yy269:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy271
			default:
				goto yy1
			}
		yy270:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy272
			default:
				goto yy43
			}
		yy271:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy273
			default:
				goto yy1
			}
		yy272:
			cursor += 1
			yych = peek(inputBytes, cursor)
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f':
				goto yy275
			default:
				goto yy43
			}
		yy273:
			cursor += 1
		yy274:
//line "_lexer.go":34
			{
				if cursor <= limit {
					tokens = append(tokens, Token{Value: input[tokenStart:cursor], Type: UUID})
				}
				continue
			}
//line "lexer.go":3733
		yy275:
			yyaccept = 8
			cursor += 1
			marker = cursor
			yych = peek(inputBytes, cursor)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy43
			default:
				goto yy274
			}
		}
//line "_lexer.go":161

	}

	return tokens
}

// Helper function to safely peek at bytes
func peek(input []byte, pos int) byte {
	if pos >= len(input) {
		return 0 // Return null byte if out of bounds
	}
	return input[pos]
}

// Helper function to check if a byte is a digit
func isDigit(b byte) bool {
	return b >= '0' && b <= '9'
}

func isHTTPCode(b string) bool {
	return len(b) == 3 && b[0] >= '0' && b[0] <= '5'
}
