name: 'CI+CD Gigapipe'

on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: Release Version
        required: true
      branch:
        description: Release Branch
        type: string
        default: 'main'
        required: true
      release:
        required: true
        type: boolean
  release:
    types: [created]

jobs:
  node:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: 'Build & Publish'
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ (github.event_name == 'workflow_dispatch') && github.event.inputs.branch || github.ref }}
      - name: build qryn-view
        uses: ./.github/actions/get-view
        env:
          TAG: v3.3.2
      - run: bash -c 'pwd && ls view/dist'
      - name: Log in to the GHCR registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Build and push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: "."
          build-args: |
            VIEW=1
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
             ghcr.io/metrico/gigapipe:latest
             ghcr.io/metrico/gigapipe:${{ (github.event_name == 'workflow_dispatch') && github.event.inputs.ref_name || github.ref_name }}
          labels: |
            dev.qryn.image.title=gigapipe
