name: Go Build CI

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: gofmt
      run: test -z "$(gofmt -l .)" || { gofmt -l .; exit 1; }

    - name: Build Gigapipe
      run: |
        go mod tidy
        CGO_ENABLED=0 go build -ldflags="-extldflags=-static" -o gigapipe cmd/gigapipe/main.go

    - name: Unit tests
      run: go test ./...

