# This workflow will validate qryn using nodejs + clickhouse

name: QRYN CI CLUSTER

on:
  push:
    branches: [ master, gigapipe ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: [ master, gigapipe ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Checkout qryn-test repository
      uses: actions/checkout@v4
      with:
        repository: metrico/qryn-test
        path: ./deps/qryn-test
    - name: Install Compose
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        version: v2.1.0 # defaults to 'latest'
        legacy: true    # will also install in PATH as `docker-compose`
    - name: Workflow Telemetry
      uses: runforesight/workflow-telemetry-action@v1.8.7 
      if: github.event_name != 'pull_request'
    - run: "make e2e-ci"
